### PR TITLE
Try to fix compilation errors on Windows/Python 2.7/64 bits.

### PR DESCRIPTION
**Pull request by notoraptor**
The last master version of libgpuarray fails to compile on Windows 8.1 64 bits for Python 2.7 with Microsoft C++ Compiler 2008. This PR tries to fix all errors I have found. **Not yet tested on Linux**.

@abergeron @nouiz

### CODE REVIEW

**Comment by notoraptor** [comment]
PS: Seems another user has found similar problems: https://github.com/Theano/libgpuarray/pull/389#issuecomment-295781542
