### ISSUE TITLE
Does not build on Mac OS X 10.10

### ISSUE THREAD

**Issue by lajash** [Theano/libgpuarray#32]
After configuring, the make command results in the following -
Scanning dependencies of target gpuarray
[ 12%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_opencl.c.o
[ 25%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_blas_opencl_clblas.c.o
[ 37%] Building C object src/CMakeFiles/gpuarray.dir/util/strb.c.o
[ 50%] Building C object src/CMakeFiles/gpuarray.dir/util/halloc.c.o
/tmp/libgpuarray/src/util/halloc.c:211:13: error: no member named 'magic' in
      'struct hblock'
  assert(p->magic == HH_MAGIC);
         ~  ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (**builtin_expect(!(e), 0) ? __assert_rtn(__func**, **FILE**, **LINE...
                        ^
/tmp/libgpuarray/src/util/halloc.c:211:22: error: use of undeclared identifier
      'HH_MAGIC'
  assert(p->magic == HH_MAGIC);
                     ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func**, **FILE**, **LINE...
                        ^
/tmp/libgpuarray/src/util/halloc.c:242:12: error: no member named 'magic' in
      'struct hblock'
        assert(b->magic == HH_MAGIC);
               ~  ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func**, **FILE**, **LINE...
                        ^
/tmp/libgpuarray/src/util/halloc.c:242:21: error: use of undeclared identifier
      'HH_MAGIC'
        assert(b->magic == HH_MAGIC);
                           ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func**, **FILE**, **LINE...
                        ^
/tmp/libgpuarray/src/util/halloc.c:251:12: error: no member named 'magic' in
      'struct hblock'
        assert(p->magic == HH_MAGIC);
               ~  ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func**, **FILE**, **LINE...
                        ^
/tmp/libgpuarray/src/util/halloc.c:251:21: error: use of undeclared identifier
      'HH_MAGIC'
        assert(p->magic == HH_MAGIC);
                           ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func**, **FILE**, __LINE...
                        ^
6 errors generated.
make[2]: **\* [src/CMakeFiles/gpuarray.dir/util/halloc.c.o] Error 1
make[1]: **\* [src/CMakeFiles/gpuarray.dir/all] Error 2
make: **\* [all] Error 2
