### ISSUE TITLE
Make documentation build with sphinx 1.6

### ISSUE THREAD

**Issue by lamblin** [Theano/libgpuarray#437]
See [here](https://travis-ci.org/Theano/libgpuarray/jobs/233044503) for an example of the failure:
```
Exception occurred:
  File "/home/travis/.local/lib/python2.7/site-packages/docutils/transforms/universal.py", line 294, in apply
    txtnode.parent.replace(txtnode, nodes.Text(newtext))
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by abergeron** [comment]
I would file that as a sphinx bug report.  Sphinx should not crash when compiling doc.

**Comment by abergeron** [comment]
Actually someone already did: https://github.com/sphinx-doc/sphinx/issues/3761

**Comment by abergeron** [comment]
This was a problem with breathe and the latest version doesn't have the issue.
